"""
Pydantic schemas for API requests and responses.
"""

import re
from enum import Enum
from typing import Optional

from pydantic import BaseModel, field_validator


class ContextType(str, Enum):
    homepage = "homepage"
    product_page = "product_page"
    cart = "cart"
    email = "email"


class EventType(str, Enum):
    click = "click"
    purchase = "purchase"
    add_to_cart = "add_to_cart"
    impression = "impression"
    playtime = "playtime"


# ── Requests ──────────────────────────────────────────────────────────────────

# Accepted user_id patterns:
#   - guest_<alphanumeric>  (generated by lib/user.js)
#   - Any alphanumeric string up to 128 characters
_USER_ID_RE = re.compile(r"^[a-zA-Z0-9_\-]{1,128}$")


class UserEventRequest(BaseModel):
    user_id: str
    item_name: str
    event_type: EventType
    playtime: float = 0.0
    metadata: dict = {}

    @field_validator("user_id")
    @classmethod
    def validate_user_id(cls, v: str) -> str:
        """
        Reject user IDs that are clearly malformed or suspiciously long.
        Valid IDs are alphanumeric strings (with _ and -) up to 128 chars,
        covering both the guest_<token> format and numeric Steam IDs.
        """
        if not _USER_ID_RE.match(v):
            raise ValueError(
                "user_id must be 1-128 alphanumeric characters "
                "(letters, digits, underscores, hyphens only)"
            )
        return v


# ── Response atoms ────────────────────────────────────────────────────────────

class RecommendedItem(BaseModel):
    item_name: str
    score: float
    reason: Optional[str] = None
    boosted: bool = False


class SimilarItem(BaseModel):
    item_name: str
    score: float


# ── Responses ─────────────────────────────────────────────────────────────────

class RecommendationResponse(BaseModel):
    recommendations: list[RecommendedItem]
    source: str
    model_version: str
    latency_ms: float
    next_page_token: Optional[str] = None


class SimilarItemsResponse(BaseModel):
    item_name: str
    similar_items: list[SimilarItem]


class EventResponse(BaseModel):
    status: str
    timestamp: float


class HealthResponse(BaseModel):
    status: str
    model_version: str
    redis_keys: int
